### ISSUE TITLE
打开闪退

### ISSUE THREAD

**Issue by Etr0-666** [Xposed-Modules-Repo/com.mhook.dialog.new#2]
出错进程:
com.mhook.dialog.new
出错线程:
AsyncTask #2
设备信息:
PACKAGE_NAME  =com.mhook.dialog.new
VERSION_CODE  =221012001
VERSION_NAME  =1.0.4
SDK           =31
RELEASE       =12
MODEL         =Redmi K30 Pro
BRAND         =Redmi
FINGERPRINT   =Redmi/lmi/lmi:12/SKQ1.211006.001/V13.0.5.0.SJKCNXM:user/release-keys
SECURITY_PATCH=2022-08-01
INCREMENTAL   =V13.0.5.0.SJKCNXM
MAGISK        =null
LSPOSED       =null
EDXPOSED      =null
XPOSED        =null
PROXY_IP      =null
PROXY_PORT    =null
PROXY_STATUS  =null
VPN_STATUS    =false
ADB_STATUS    =true
NET_STATUS    =true
NET_PER_STAT  =true
ROOT          =unknown
CPU           =armeabi-v7a armeabi

出错信息:
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
出错堆栈:
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
	at org.json.JSONObject.<init>(JSONObject.java:168)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at i.ᵢˎ.ʼ(SourceFile:950)
	at i.ᵢˎ.ʻ(Unknown Source:0)
	at i.ᵢˋ.run(SourceFile:7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

开启模块后直接闪退
这是在卸载重装后才能负责抛出的异常

**Comment by serifer** [comment]
更新到新版试试
